### ISSUE TITLE
Facing Bug while migrating db

### ISSUE THREAD

**Issue by Fatima-hub333** [MusheAbdulHakim/Laravel-Smarthr#14]
Hi, I am facing an issue while migrating the database "php artisan migrate --seed" while running this command facing the attached below issue, kindly help me in this error, how can I resolve it?
![bug](https://user-images.githubusercontent.com/89512061/200108013-59bb09cf-5b0a-41a2-9238-4e923dc09c13.png)

**Comment by MusheAbdulHakim** [comment]
you have to create the database 'smarthr' before running migrations.

set the appropriate values for the following environment variables:
```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=smarthr
DB_USERNAME=root
DB_PASSWORD=
```
make sure the value for DB_DATABASE is the name of the database you created. And also set the username and password to your database.

**Comment by Fatima-hub333** [comment]
> you have to create the database 'smarthr' before running migrations.
> 
> set the appropriate values for the following environment variables:
> 
> ```
> DB_CONNECTION=mysql
> DB_HOST=127.0.0.1
> DB_PORT=3306
> DB_DATABASE=smarthr
> DB_USERNAME=root
> DB_PASSWORD=
> ```
> 
> make sure the value for DB_DATABASE is the name of the database you created. And also set the username and password to your database.

I did this. I create DB with the name of 'smarthr' and after that run this command
