### ISSUE TITLE
query: Thumb attendance machine

### ISSUE THREAD

**Issue by Fatima-hub333** [MusheAbdulHakim/Laravel-Smarthr#15]
Is this possible to fetch attendance data from the Thumb attendance machine?

**Comment by MusheAbdulHakim** [comment]
Not yet but maybe we could have something like that in the future.

**Comment by MusheAbdulHakim** [comment]
Hi. Just reaching out again to find out if you were able to set up the
application successfully.
If not, you can schedule some time let's connect via zoom or google meet. I
will be happy to help you set up the application.
Best Regards.
