### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by genesisoliva** [MusheAbdulHakim/Laravel-Smarthr#3]
I used XAMPP and I don’t know which folder directory am I running the repo…

**Comment by MusheAbdulHakim** [comment]
the public directory is the one you should access through the browser.
so it will look like this : "localhost/Laravel-Smarthr/public" or you can use the laravel buildin server.
change Laravel-Smarthr if you happen to change the folder name after cloning or downloading.

**Comment by genesisoliva** [comment]
This is what I get 

Warning: require(C:\xampp\htdocs\Laravel-Smarthr\public/../vendor/autoload.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\Laravel-Smarthr\public\index.php on line 34

Fatal error: Uncaught Error: Failed opening required 'C:\xampp\htdocs\Laravel-Smarthr\public/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\Laravel-Smarthr\public\index.php:34 Stack trace: #0 {main} thrown in C:\xampp\htdocs\Laravel-Smarthr\public\index.php on line 34
