### ISSUE TITLE
Roles and Permission not updating

### ISSUE THREAD

**Issue by MACKIE199X** [MusheAbdulHakim/Laravel-Smarthr#33]
Hi @MusheAbdulHakim,

The problem with roles continues to exist. The roles is already updating in the database but thr selection is not displaying in the sidebar menu. 

 
![Screenshot 2024-08-27 144636](https://github.com/user-attachments/assets/2f03491a-8676-4185-b5eb-5a91276cb5a5)
![Screenshot 2024-08-27 145257](https://github.com/user-attachments/assets/b29ff378-a798-4680-af58-225a382b9f4f)
![Screenshot 2024-08-27 145035](https://github.com/user-attachments/assets/1f347c8e-8d8d-4f60-9b5e-cf8e63dcb635)

**Comment by MusheAbdulHakim** [comment]
Have you try updating the existing users?. Or adding a new user (employee or client or user) to the system and login as that user.

Please try it out and let me know the result

**Comment by MACKIE199X** [comment]
Updating existing users and creating new employees work this time. Thank you, Mushe!

**Comment by MusheAbdulHakim** [comment]
Alright
