### ISSUE TITLE
 The chat app is not functional,Thank you so much!

### ISSUE THREAD

**Issue by misganaw-negash** [MusheAbdulHakim/Laravel-Smarthr#34]

**Comment by MusheAbdulHakim** [comment]
Please elaborate more on the issue you are facing. Add code samples if any. 
Make sure to follow the installation instructions very well. The chat app utilizes [Reverb](https://laravel.com/docs/11.x/reverb) to make sure it's running.
Without more information on the issue, I am closing it. Feel free to reopen it with more details
