### ISSUE TITLE
WorldSeeder Fatal error

### ISSUE THREAD

**Issue by Ynn0** [MusheAbdulHakim/Laravel-Smarthr#36]
I am a newbie with programming so I can't really solve this alone.

Here's the error I am receiving on my end.

Database\Seeders\WorldSeeder ............................................................................................................. RUNNING

   Symfony\Component\ErrorHandler\Error\FatalError 

  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes)

  at vendor\nnjeim\world\src\Actions\SeedAction.php:125
    121▕                        // import json data.
    122▕                        $moduleSourcePath = __DIR__ . '/../../resources/json/' . $module . '.json';
    123▕
    124▕                        if (File::exists($moduleSourcePath)) {
  ➜ 125▕                                $this->modules[$module]['data'] = json_decode(File::get($moduleSourcePath), true);
    126▕                        }
    127▕                }
    128▕        }
    129▕

  1   vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php:245
      Symfony\Component\ErrorHandler\Error\FatalError::__construct("'Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes)'", "0", "['type' => 1, 'message' => 'Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes)', 'file' => 'C:\\wamp64\\www\\smarthr\\vendor\\nnjeim\\world\\src\\Actions\\SeedAction.php', 'line' => 125]", "0", "???", "???")

  2   vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php:232
      Illuminate\Foundation\Bootstrap\HandleExceptions::fatalErrorFromPhpError("['type' => 1, 'message' => 'Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes)', 'file' => 'C:\\wamp64\\www\\smarthr\\vendor\\nnjeim\\world\\src\\Actions\\SeedAction.php', 'line' => 125]", "0")

   Whoops\Exception\ErrorException 

  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes)

  at vendor\nnjeim\world\src\Actions\SeedAction.php:125
    121▕                        // import json data.
    122▕                        $moduleSourcePath = __DIR__ . '/../../resources/json/' . $module . '.json';
    123▕
    124▕                        if (File::exists($moduleSourcePath)) {
  ➜ 125▕                                $this->modules[$module]['data'] = json_decode(File::get($moduleSourcePath), true);
    126▕                        }
    127▕                }
    128▕        }
    129▕

  1   vendor\filp\whoops\src\Whoops\Run.php:510
      Whoops\Run::handleError("Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes)", "C:\wamp64\www\smarthr\vendor\nnjeim\world\src\Actions\SeedAction.php")

  2   [internal]:0
      Whoops\Run::handleShutdown()

![image](https://github.com/user-attachments/assets/f3dcffac-551d-4880-9b33-1d01be1794ef)
![image](https://github.com/user-attachments/assets/d176ae05-97a3-40f2-906e-ffbfd471fbdc)

**Comment by MusheAbdulHakim** [comment]
Update the memory_limit of your php.ini file.
After that, restart your server.
so you can set it to something like: **memory_limit=1024M**

**Comment by Ynn0** [comment]
Hey, I solved it. Thanks your project is really good sensei.

> Update the memory_limit of your php.ini file. After that, restart your server. so you can set it to something like: **memory_limit=1024M**
