### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by genesisoliva** [MusheAbdulHakim/Laravel-Smarthr#4]
When I login it says this

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.deleted_at' in 'where clause' (SQL: select * from `users` where `email` = admin@admin.com and `users`.`deleted_at` is null limit 1)

**Comment by MusheAbdulHakim** [comment]
have you read the repository read me?.

**Comment by MusheAbdulHakim** [comment]
if you follow the steps on the repository page and you won't have any of these problems

**Comment by MusheAbdulHakim** [comment]
i have added database dump file in the db folder just import it in phpmyadmin and you should be able to login.
